// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

interface Course {
  id: string;
  name: string;
  level: string;
}

interface EmbeddedCourses {
  courses: Course[];
}

interface CoursesApiResponse {
  _embedded: EmbeddedCourses
  total: number;
  skip: number;
  limit: number;
}

// Define a service using a base URL and expected endpoints
export const coursesApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:8080/courses" }),
  reducerPath: "coursesApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Course", "Course"],
  endpoints: (build) => ({
    // Supply generics for the return type (in this case `CoursesApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getCourses: build.query<CoursesApiResponse, number>({
      query: (limit = 10) => `?size=${limit}`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, error, id) => [{ type: "Course", id }],
    }),
    getCourse: build.query<Course, string>({
      query: (id) => `/${id}`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, error, id) => [{ type: "Course", id }],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `coursesApiSlice.endpoints.getCourses.useQuery`
export const { useGetCoursesQuery: useGetCoursesQuery, useGetCourseQuery } = coursesApiSlice;
